/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UserRouteRouteImport } from './routes/_user/route'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as UserIndexRouteImport } from './routes/_user/index'
import { Route as UserContactRouteImport } from './routes/_user/contact'
import { Route as UserBlogRouteImport } from './routes/_user/blog'
import { Route as UserAboutRouteImport } from './routes/_user/about'
import { Route as UserPropertiesIndexRouteImport } from './routes/_user/properties.index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as UserPropertiesSlugRouteImport } from './routes/_user/properties.$slug'

const UserRouteRoute = UserRouteRouteImport.update({
  id: '/_user',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserIndexRoute = UserIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UserRouteRoute,
} as any)
const UserContactRoute = UserContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => UserRouteRoute,
} as any)
const UserBlogRoute = UserBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => UserRouteRoute,
} as any)
const UserAboutRoute = UserAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => UserRouteRoute,
} as any)
const UserPropertiesIndexRoute = UserPropertiesIndexRouteImport.update({
  id: '/properties/',
  path: '/properties/',
  getParentRoute: () => UserRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const UserPropertiesSlugRoute = UserPropertiesSlugRouteImport.update({
  id: '/properties/$slug',
  path: '/properties/$slug',
  getParentRoute: () => UserRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof UserIndexRoute
  '/about': typeof UserAboutRoute
  '/blog': typeof UserBlogRoute
  '/contact': typeof UserContactRoute
  '/admin/': typeof AdminIndexRoute
  '/properties/$slug': typeof UserPropertiesSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/properties/': typeof UserPropertiesIndexRoute
}
export interface FileRoutesByTo {
  '/about': typeof UserAboutRoute
  '/blog': typeof UserBlogRoute
  '/contact': typeof UserContactRoute
  '/': typeof UserIndexRoute
  '/admin': typeof AdminIndexRoute
  '/properties/$slug': typeof UserPropertiesSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/properties': typeof UserPropertiesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_user': typeof UserRouteRouteWithChildren
  '/_user/about': typeof UserAboutRoute
  '/_user/blog': typeof UserBlogRoute
  '/_user/contact': typeof UserContactRoute
  '/_user/': typeof UserIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/_user/properties/$slug': typeof UserPropertiesSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_user/properties/': typeof UserPropertiesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/admin/'
    | '/properties/$slug'
    | '/api/auth/$'
    | '/properties/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/about'
    | '/blog'
    | '/contact'
    | '/'
    | '/admin'
    | '/properties/$slug'
    | '/api/auth/$'
    | '/properties'
  id:
    | '__root__'
    | '/_user'
    | '/_user/about'
    | '/_user/blog'
    | '/_user/contact'
    | '/_user/'
    | '/admin/'
    | '/_user/properties/$slug'
    | '/api/auth/$'
    | '/_user/properties/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  UserRouteRoute: typeof UserRouteRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_user': {
      id: '/_user'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof UserRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_user/': {
      id: '/_user/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof UserIndexRouteImport
      parentRoute: typeof UserRouteRoute
    }
    '/_user/contact': {
      id: '/_user/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof UserContactRouteImport
      parentRoute: typeof UserRouteRoute
    }
    '/_user/blog': {
      id: '/_user/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof UserBlogRouteImport
      parentRoute: typeof UserRouteRoute
    }
    '/_user/about': {
      id: '/_user/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof UserAboutRouteImport
      parentRoute: typeof UserRouteRoute
    }
    '/_user/properties/': {
      id: '/_user/properties/'
      path: '/properties'
      fullPath: '/properties/'
      preLoaderRoute: typeof UserPropertiesIndexRouteImport
      parentRoute: typeof UserRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_user/properties/$slug': {
      id: '/_user/properties/$slug'
      path: '/properties/$slug'
      fullPath: '/properties/$slug'
      preLoaderRoute: typeof UserPropertiesSlugRouteImport
      parentRoute: typeof UserRouteRoute
    }
  }
}

interface UserRouteRouteChildren {
  UserAboutRoute: typeof UserAboutRoute
  UserBlogRoute: typeof UserBlogRoute
  UserContactRoute: typeof UserContactRoute
  UserIndexRoute: typeof UserIndexRoute
  UserPropertiesSlugRoute: typeof UserPropertiesSlugRoute
  UserPropertiesIndexRoute: typeof UserPropertiesIndexRoute
}

const UserRouteRouteChildren: UserRouteRouteChildren = {
  UserAboutRoute: UserAboutRoute,
  UserBlogRoute: UserBlogRoute,
  UserContactRoute: UserContactRoute,
  UserIndexRoute: UserIndexRoute,
  UserPropertiesSlugRoute: UserPropertiesSlugRoute,
  UserPropertiesIndexRoute: UserPropertiesIndexRoute,
}

const UserRouteRouteWithChildren = UserRouteRoute._addFileChildren(
  UserRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  UserRouteRoute: UserRouteRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
